### ISSUE TITLE
EstherParametersClass To-Do

### ISSUE THREAD

**Issue by richardbriggs** [PaNOSC-ViNYL/SimEx#126]
Need to ensure that each ablating material runs at optimum settings; this is the most crucial aspect of the hydrocode simulations. Documentation of each ablator and relevant laser conditions can be a useful tool to be included in the wiki. (i.e. What pressure can you achieve with different ablators for a variety of laser conditions? etc.).

**Comment by richardbriggs** [comment]
- [ ] Allow user to set feathering options for low/high spatial resolution
- [ ] Add expert mode to EOS options (choose BLF or SESAME where available)
- [ ] Number of layers debugging to ensure the vacuum space is added correctly
- [x] Ensure flat top, quasi flat top, ramp pulse shapes are created properly in _serialize.

**Comment by richardbriggs** [comment]
Moved all to issue #129, which remains open
