### ISSUE TITLE
EstherParametersClass: To-Do and Enhancements

### ISSUE THREAD

**Issue by richardbriggs** [PaNOSC-ViNYL/SimEx#129]
Enhancements that are less critical but will be important for the ESRF high power laser project starting June 2018 (and for further user modification of experimental parameters etc.)

# Primary to-do
- [x] Add expert mode to EOS options (choose BLF or SESAME where available)
- [x] Allow user to set feathering options for low/high spatial resolution
- [ ] Retrieve P-T conditions for a specific time delay -> use openPMD plugin for visit
- [x] Refractive index options for each ablator
- [x] Number of layers debugging to ensure the vacuum space is added correctly
# Secondary to-do
- [ ] User defined laser pulses
- [x] Initial settings for expert mode (rad_transfer, without_therm_conductivity etc.)
- [ ] Determine breakout time for expected VISAR signals
- [x] Ensure flat top, quasi flat top, ramp pulse shapes are created properly in _serialize.
