### ISSUE TITLE
Completion of the long-pulse pump-probe s2e simulation toolchain

### ISSUE THREAD

**Issue by CFGrote** [PaNOSC-ViNYL/SimEx#145]
## Outline
The radiation hydrodynamics simulations are currently isolated from other simulation tools. Output is written to openpmd conform hdf5. Those data should now be picked up by an electronic structure/MD calculator and, subsequently, atomistic signal generator, or directly by a continuum signal generator such as XRTS.

## Tasks
- [ ] Implement an API to (AI)MD tools (consider ASE)
- [ ] Enable feeding of rad-hydro rho-T-p profiles into electronic structure/MD calculators.
- [ ] openPMD extension for storage of MD + electronic structure data
- [ ] Enable feeding electronic structure + MD data into signal generators (FEFF, Diffractors)
- [ ] Prototype XRTS simulation from rad-hydro rho-T-p profiles with PlasmaXRTSCalculator
